# Generated by Django 5.2.10 on 2026-01-14 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物件名')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('rent', models.CharField(max_length=50, verbose_name='家賃')),
                ('latitude', models.FloatField(verbose_name='緯度')),
                ('longitude', models.FloatField(verbose_name='経度')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
